GET http://localhost:3000/api/comments

###
GET http://localhost:3000/api/comments/:id

###
POST http://localhost:3000/api/comments
Content-Type: application/json
 
{
  "content": "Lorem ipsum odor amet, consectetuer adipiscing elit. Felis bibendum praesent mus fringilla tortor volutpat.",
  "postId": "",
  "userId": ""
}

###
PUT http://localhost:3000/api/comments/:id
Content-Type: application/json

{
  "content": "Lorem ipsum odor amet, consectetuer adipiscing elit. Felis bibendum praesent mus fringilla tortor volutpat.",
  "userId": "0"
}

###
DELETE http://localhost:3000/api/comments/:id