GET http://localhost:3000/api/replies

###
GET http://localhost:3000/api/replies/:id

###
POST http://localhost:3000/api/replies
Content-Type: application/json
 
{
  "content": "Lorem ipsum odor amet, consectetuer adipiscing elit. Felis bibendum praesent mus fringilla tortor volutpat.",
  "commentId": "",
  "userId": ""
}

###
PUT http://localhost:3000/api/replies/:id
Content-Type: application/json

{
  "content": "Lorem ipsum odor amet, consectetuer adipiscing elit. Felis bibendum praesent mus fringilla tortor volutpat.",
  "userId": "0"
}

###
DELETE http://localhost:3000/api/replies/:id