GET http://localhost:3000/api/users

###
GET http://localhost:3000/api/users/142a4a3e-0a9a-432b-ab00-faa070e7f0b2

###
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "Jane Doe",
  "email": "jane.doe@example.com"
}

###
PUT http://localhost:3000/api/users/:id
Content-Type: application/json

{
  "name": "Jane Marino",
  "email": "jane.marino@example.com"
}

###
DELETE http://localhost:3000/api/users/:id